[phases.setup]
nixPkgs = ["dotnet-sdk_9"]

[phases.build]
cmds = [
    "cd NordenAPI",
    "dotnet restore",
    "dotnet build -c Release",
    "dotnet publish -c Release -o ./publish"
]

[start]
cmd = "cd NordenAPI && dotnet ./publish/NordenAPI.dll --urls http://0.0.0.0:$PORT"
